# Generated by Django 5.2 on 2025-05-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nickname',
        ),
    ]
